sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t hv6kyh/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true hv6kyh/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success!"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-979312597187"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
